//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerConfig
{
    using System;
    using System.Collections.Generic;
    
    public partial class Components
    {
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public double cost { get; set; }
        public bool availability { get; set; }
        public int cat_id { get; set; }
        public int type_id { get; set; }
        public byte[] image { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Types Types { get; set; }
    }
}
